# Generated by Django 6.0.7 on 2026-08-19 04:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='branches', to=settings.AUTH_USER_MODEL),
        ),
    ]
