# Generated by Django 6.0.7 on 2026-09-04 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_branch_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='organization.branch')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('branch', 'name'), name='unique_department_per_branch')],
            },
        ),
    ]
