# Generated by Django 6.0.7 on 2026-08-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employee_salary_employee_daily_wage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='biweekly_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
