# Generated by Django 6.0.7 on 2026-08-20 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_branch'),
        ('organization', '0002_branch_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='organization.branch'),
        ),
    ]
