# Generated by Django 6.0.7 on 2026-08-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employeeidentityproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeidentityproof',
            name='cloudinary_resource_type',
            field=models.CharField(default='image', max_length=20),
        ),
    ]
