# Generated by Django 6.0.7 on 2026-09-03 09:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employeeidentityproof_cloudinary_resource_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalaryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_type', models.CharField(choices=[('MONTHLY', 'Monthly'), ('DAILY', 'Daily'), ('BIWEEKLY', '15 Days')], max_length=20)),
                ('monthly_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('daily_wage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('biweekly_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_changes', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_history', to='employees.employee')),
            ],
            options={
                'ordering': ['-effective_from'],
            },
        ),
    ]
