# Generated by Django 6.0.7 on 2026-09-07 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_financialaccount_financialtransaction_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='financialaccount',
            new_name='fin_acct_branch_type_idx',
            old_name='financial_account_branch_type_idx',
        ),
    ]
