# Generated by Django 6.0.7 on 2026-09-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_rename_financial_account_branch_type_idx_fin_acct_branch_type_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccount',
            name='opening_balance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
