# Generated by Django 6.0.7 on 2026-09-10 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_financialtransaction_idempotency_key_and_more'),
        ('organization', '0003_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField()),
                ('total_gross', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted')], default='DRAFT', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_sales', to='organization.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_daily_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-business_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DailySalesPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('FOOD_DELIVERY', 'Food Delivery')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('platform', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_sales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='expenses.dailysales')),
            ],
        ),
        migrations.AddIndex(
            model_name='dailysales',
            index=models.Index(fields=['branch', 'business_date'], name='daily_sales_branch_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailysales',
            constraint=models.UniqueConstraint(fields=('branch', 'business_date'), name='unique_daily_sales_per_branch_date'),
        ),
        migrations.AddIndex(
            model_name='dailysalespayment',
            index=models.Index(fields=['daily_sales', 'payment_method'], name='daily_payment_sales_method_idx'),
        ),
    ]
