# Generated by Django 6.0.7 on 2026-09-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_dailysales_dailysalespayment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialaccount',
            name='account_type',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('UPI', 'UPI'), ('RECEIVABLE', 'Receivable'), ('PETTY_CASH', 'Petty Cash')], max_length=20),
        ),
    ]
