# Generated by Django 6.0.7 on 2026-09-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_alter_financialaccount_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccount',
            name='account_purpose',
            field=models.CharField(choices=[('GENERAL', 'General'), ('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD_RECEIVABLE', 'Card Receivable'), ('FOOD_DELIVERY_RECEIVABLE', 'Food Delivery Receivable')], default='GENERAL', max_length=30),
        ),
    ]
