# Generated by Django 6.0.7 on 2026-09-11 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_financialaccount_account_purpose'),
        ('organization', '0003_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('settled_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_SETTLED', 'Partially Settled'), ('SETTLED', 'Settled')], default='PENDING', max_length=20)),
                ('business_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='organization.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_receivables', to=settings.AUTH_USER_MODEL)),
                ('daily_sales', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='expenses.dailysales')),
                ('receivable_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivable_records', to='expenses.financialaccount')),
            ],
            options={
                'ordering': ['-business_date', '-id'],
                'indexes': [models.Index(fields=['branch', 'status', 'business_date'], name='receivable_branch_status_date_idx'), models.Index(fields=['receivable_account', 'status'], name='receivable_account_status_idx')],
            },
        ),
    ]
