# Generated by Django 6.0.7 on 2026-09-11 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_receivable'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='receivable',
            new_name='recv_branch_status_date_idx',
            old_name='receivable_branch_status_date_idx',
        ),
        migrations.RenameIndex(
            model_name='receivable',
            new_name='recv_account_status_idx',
            old_name='receivable_account_status_idx',
        ),
    ]
