# Generated by Django 6.0.7 on 2026-09-11 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_rename_receivable_branch_status_date_idx_recv_branch_status_date_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receivable',
            name='daily_sales',
        ),
        migrations.AddField(
            model_name='receivable',
            name='daily_sales_payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receivable', to='expenses.dailysalespayment'),
        ),
    ]
