# Generated by Django 6.0.7 on 2026-09-11 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_remove_receivable_daily_sales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivable',
            name='daily_sales_payment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receivable', to='expenses.dailysalespayment'),
        ),
    ]
