# Generated by Django 6.0.7 on 2026-09-11 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0013_alter_receivable_daily_sales_payment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivableSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('received_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('settlement_date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_receivable_settlements', to=settings.AUTH_USER_MODEL)),
                ('destination_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivable_settlements', to='expenses.financialaccount')),
                ('receivable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='expenses.receivable')),
            ],
            options={
                'ordering': ['-settlement_date', '-id'],
                'indexes': [models.Index(fields=['receivable', 'settlement_date'], name='recv_settle_date_idx'), models.Index(fields=['destination_account', 'settlement_date'], name='recv_settle_account_date_idx')],
            },
        ),
    ]
