# Generated by Django 6.0.7 on 2026-09-12 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0014_receivablesettlement'),
        ('organization', '0003_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_partners', to='organization.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_delivery_partners', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryPartnerCommissionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_delivery_partner_rates', to=settings.AUTH_USER_MODEL)),
                ('delivery_partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commission_rates', to='expenses.deliverypartner')),
            ],
            options={
                'ordering': ['-effective_from', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='deliverypartner',
            index=models.Index(fields=['branch', 'is_active'], name='delivery_partner_branch_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliverypartner',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='unique_delivery_partner_per_branch'),
        ),
        migrations.AddIndex(
            model_name='deliverypartnercommissionrate',
            index=models.Index(fields=['delivery_partner', 'effective_from'], name='delivery_partner_rate_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliverypartnercommissionrate',
            constraint=models.UniqueConstraint(fields=('delivery_partner', 'effective_from'), name='unique_delivery_partner_rate_start'),
        ),
    ]
