# Generated by Django 6.0.7 on 2026-09-12 06:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0015_deliverypartner_deliverypartnercommissionrate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deliverypartnercommissionrate',
            name='unique_delivery_partner_rate_start',
        ),
        migrations.RenameIndex(
            model_name='deliverypartnercommissionrate',
            new_name='del_partner_rate_date_idx',
            old_name='delivery_partner_rate_date_idx',
        ),
        migrations.AddConstraint(
            model_name='deliverypartnercommissionrate',
            constraint=models.UniqueConstraint(fields=('delivery_partner', 'effective_from'), name='unique_del_partner_rate_start'),
        ),
    ]
