# Generated by Django 6.0.7 on 2026-09-12 06:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0016_remove_deliverypartnercommissionrate_unique_delivery_partner_rate_start_and_more'),
        ('organization', '0003_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deliverypartner',
            name='unique_delivery_partner_per_branch',
        ),
        migrations.RenameIndex(
            model_name='deliverypartner',
            new_name='del_partner_branch_active_idx',
            old_name='delivery_partner_branch_active_idx',
        ),
        migrations.AddConstraint(
            model_name='deliverypartner',
            constraint=models.UniqueConstraint(fields=('branch', 'name'), name='unique_del_partner_per_branch'),
        ),
    ]
