# Generated by Django 6.0.7 on 2026-09-12 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0017_remove_deliverypartner_unique_delivery_partner_per_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysalespayment',
            name='delivery_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='daily_sales_payments', to='expenses.deliverypartner'),
        ),
    ]
