# Generated by Django 6.0.7 on 2026-09-12 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0019_receivable_commission_amount_and_more'),
        ('organization', '0003_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='organization.branch'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['branch', 'expense_date'], name='expense_branch_date_idx'),
        ),
    ]
