# Generated by Django 6.0.7 on 2026-09-12 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0020_expense_branch_expense_expense_branch_date_idx'),
        ('organization', '0003_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='organization.branch'),
        ),
    ]
