# Generated by Django 6.0.7 on 2026-09-12 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0021_alter_expense_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.financialaccount'),
            preserve_default=False,
        ),
    ]
