# Generated by Django 6.0.7 on 2026-09-15 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0022_expense_payment_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('old_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('old_expense_date', models.DateField()),
                ('old_description', models.TextField(blank=True)),
                ('new_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_expense_date', models.DateField()),
                ('new_description', models.TextField(blank=True)),
                ('reason', models.TextField()),
                ('rejection_reason', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_expense_adjustments', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adjustments', to='expenses.expense')),
                ('new_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_expense_adjustments', to='expenses.expensecategory')),
                ('new_payment_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_expense_adjustments', to='expenses.financialaccount')),
                ('old_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='old_expense_adjustments', to='expenses.expensecategory')),
                ('old_payment_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='old_expense_adjustments', to='expenses.financialaccount')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_expense_adjustments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at', '-id'],
                'indexes': [models.Index(fields=['expense', 'status'], name='expense_adj_expense_status_idx'), models.Index(fields=['status', 'requested_at'], name='expense_adj_status_date_idx')],
            },
        ),
    ]
