# Generated by Django 6.0.7 on 2026-09-06 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advance', '0002_advance_approved_at_advance_approved_by_and_more'),
        ('employees', '0009_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='advances', to='employees.employee'),
        ),
    ]
