# Generated by Django 6.0.7 on 2026-09-16 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_purchaseitem_unit_price'),
        ('organization', '0003_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='organization.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_status',
            field=models.CharField(choices=[('CREDIT', 'Credit'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid')], default='CREDIT', max_length=10),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger_entries', to='organization.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockusage',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='stock_usages', to='organization.branch'),
            preserve_default=False,
        ),
    ]
