# Generated by Django 6.0.7 on 2026-09-24 04:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_purchase_branch_purchase_payment_status_and_more'),
        ('organization', '0003_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('operation', models.CharField(max_length=100)),
                ('request_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('resource_type', models.CharField(blank=True, max_length=100)),
                ('resource_id', models.PositiveIntegerField(blank=True, null=True)),
                ('response_status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('INCREASE', 'Increase'), ('DECREASE', 'Decrease')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('adjustment_date', models.DateField()),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='balance_before',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_ledger_entries_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='reference_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='stockusage',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_usages_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['branch', 'purchase_date'], name='inventory_p_branch__7b1db6_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['supplier', 'purchase_date'], name='inventory_p_supplie_f9e5f3_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseitem',
            index=models.Index(fields=['purchase', 'product'], name='inventory_p_purchas_08ded3_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['branch', 'product', 'movement_date'], name='inventory_s_branch__c07195_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['movement_type', 'movement_date'], name='inventory_s_movemen_c29df1_idx'),
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['reference_type', 'reference_id'], name='inventory_s_referen_6e609d_idx'),
        ),
        migrations.AddIndex(
            model_name='stockusage',
            index=models.Index(fields=['branch', 'usage_date'], name='inventory_s_branch__2cd25d_idx'),
        ),
        migrations.AddIndex(
            model_name='stockusage',
            index=models.Index(fields=['product', 'usage_date'], name='inventory_s_product_70d65a_idx'),
        ),
        migrations.AddField(
            model_name='idempotencyrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_idempotency_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockadjustment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_adjustments', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='organization.branch'),
        ),
        migrations.AddField(
            model_name='stockbalance',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_balances', to='inventory.product'),
        ),
        migrations.AddIndex(
            model_name='idempotencyrecord',
            index=models.Index(fields=['user', 'operation', 'created_at'], name='inventory_i_user_id_e02db5_idx'),
        ),
        migrations.AddIndex(
            model_name='idempotencyrecord',
            index=models.Index(fields=['expires_at'], name='inventory_i_expires_ab974c_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['branch', 'product'], name='inventory_s_branch__a163fb_idx'),
        ),
        migrations.AddIndex(
            model_name='stockadjustment',
            index=models.Index(fields=['adjustment_date'], name='inventory_s_adjustm_ec33d6_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockadjustment',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='stock_adjustment_quantity_positive'),
        ),
        migrations.AddIndex(
            model_name='stockbalance',
            index=models.Index(fields=['product'], name='inventory_s_product_fdf214_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('branch', 'product'), name='unique_stock_balance_branch_product'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='stock_balance_quantity_non_negative'),
        ),
    ]
