# Generated by Django 6.0.7 on 2026-08-03 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Salary',
        ),
    ]
