# Generated by Django 6.0.7 on 2026-08-05 07:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
