# Generated by Django 6.0.7 on 2026-08-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0004_salary_generated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='half_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='salary',
            name='leave_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
