# Generated by Django 6.0.7 on 2026-09-02 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employeeidentityproof_cloudinary_resource_type'),
        ('salary', '0005_salary_half_days_salary_leave_days'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salary',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='salary',
            name='attendance_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='salary',
            name='other_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='salary',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payrolls', to='employees.employee'),
        ),
        migrations.AddIndex(
            model_name='salary',
            index=models.Index(fields=['year', 'month'], name='salary_year_month_idx'),
        ),
        migrations.AddIndex(
            model_name='salary',
            index=models.Index(fields=['employee', 'year', 'month'], name='salary_employee_period_idx'),
        ),
        migrations.AddIndex(
            model_name='salary',
            index=models.Index(fields=['status', 'year', 'month'], name='salary_status_period_idx'),
        ),
        migrations.AddConstraint(
            model_name='salary',
            constraint=models.UniqueConstraint(fields=('employee', 'month', 'year'), name='unique_salary_per_employee_month'),
        ),
    ]
