# Generated by Django 6.0.7 on 2026-09-02 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0006_alter_salary_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='generated_at',
        ),
    ]
