# Generated by Django 6.0.7 on 2026-08-29 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('employees', '0007_employeeidentityproof_cloudinary_resource_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='check_in',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_out',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='employees.employee'),
        ),
    ]
