# Generated by Django 6.0.7 on 2026-09-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_attendance_check_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
    ]
